### ISSUE TITLE
Can't use custom items while mod is enabled.

### ISSUE THREAD

**Issue by tuntor689** [KacperObara/H3VR_Zombie_Gamemode#3]
When the mod is enabled on thunderstore, I am unable to use custom items via the item spawner. When it is disabled, custom items work perfectly fine.

**Comment by KacperObara** [comment]
I couldn't recreate Your issue, I managed to spawn custom FG 42 while the mod was enabled. Could You try again and send the logs? Logs should be in this directory:
C:\Users\<YourName>\AppData\Roaming\r2modmanPlus-local\H3VR\profiles\Default\BepInEx\LogOutput.log

**Comment by KacperObara** [comment]
Also Your R2Modman profile might help so I can check with the exact same mods
https://www.youtube.com/watch?v=YU6TZuteaVg

**Comment by tuntor689** [comment]
[LogOutput.log](https://github.com/KacperObara/H3VR_Zombie_Gamemode/files/7530618/LogOutput.log)
PF CODE: I6PVeuGTdS

**Comment by tuntor689** [comment]
shit i accidentally closed it

**Comment by tuntor689** [comment]
Turns out if I load into Proving Ground before hand, custom items work fine. If I go into any special game modes like TnH and Nacht Der Untoten first thing, they just don't load for some reason. Loading them after Proving Ground seems to work fine.

**Comment by KacperObara** [comment]
I was able to reproduce this bug, thank you. But it's really bizarre.
- Cod zombies + Doom weapons mod - weapons NOT working.
- Cod zombies + Doom weapons + FG42 - weapons working.
- Doom weapons - weapons NOT working
- Doom weapons + FG42 - weapons working

At this point I'm starting to think that there is problem with something else, and my mod just happened to be one of those breaking stuff. Unless there is some junk left even after uninstalling my own mod.

This is my profile with only doom weapons and no zombies: TiIWlclesx
If it breaks for You, that must mean it's not zombies fault (probably?)

**Comment by KacperObara** [comment]
It appears that mods are generally broken now because of the alpha update. I should catch that earlier, but it's my first time dealing with h3vr alpha's.
